// Bundles ../data/world.md + ../data/characters/*.md into src/data.js.
// Runs before `wrangler dev` and `wrangler deploy` (see package.json scripts).
// Re-run any time world or character markdown changes; deploy to apply.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "..");
const WORLD_FILE = join(REPO, "data", "world.md");
const CHARS_DIR = join(REPO, "data", "characters");
const OUT_FILE = join(HERE, "src", "data.js");

function parseFrontmatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) return { meta: {}, body: text };
  const meta = {};
  for (const line of m[1].split("\n")) {
    const i = line.indexOf(":");
    if (i === -1) continue;
    const key = line.slice(0, i).trim();
    let val = line.slice(i + 1).trim();
    if ((val.startsWith("'") && val.endsWith("'")) || (val.startsWith('"') && val.endsWith('"'))) {
      val = val.slice(1, -1);
    }
    meta[key] = val;
  }
  return { meta, body: m[2] };
}

const world = readFileSync(WORLD_FILE, "utf8");

const characters = {};
for (const file of readdirSync(CHARS_DIR).sort()) {
  if (!file.endsWith(".md")) continue;
  const id = file.replace(/\.md$/, "");
  const raw = readFileSync(join(CHARS_DIR, file), "utf8");
  const { meta, body } = parseFrontmatter(raw);
  characters[id] = { meta, body };
}

const banner = `// AUTO-GENERATED by build-data.mjs — do not edit by hand.\n` +
               `// Source: ../data/world.md and ../data/characters/*.md\n`;

const out =
  banner +
  `export const WORLD = ${JSON.stringify(world)};\n` +
  `export const CHARACTERS = ${JSON.stringify(characters, null, 2)};\n`;

writeFileSync(OUT_FILE, out);
console.log(`wrote ${OUT_FILE} — ${Object.keys(characters).length} characters, ${world.length} char world`);
