// Bundles ../data/world.md + ../data/characters/**/*.md into src/data.js.
// Runs before `wrangler dev` and `wrangler deploy` (see package.json scripts).
// Re-run any time world or character markdown changes; deploy to apply.

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "..");
const WORLD_FILE = join(REPO, "data", "world.md");
const CHARS_DIR = join(REPO, "data", "characters");
const OUT_FILE = join(HERE, "src", "data.js");

function parseFrontmatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) return { meta: {}, body: text };
  const meta = {};
  for (const line of m[1].split("\n")) {
    const i = line.indexOf(":");
    if (i === -1) continue;
    const key = line.slice(0, i).trim();
    let val = line.slice(i + 1).trim();
    if ((val.startsWith("'") && val.endsWith("'")) || (val.startsWith('"') && val.endsWith('"'))) {
      val = val.slice(1, -1);
    }
    meta[key] = val;
  }
  return { meta, body: m[2] };
}

// Every .md under characters/, including subfolders like characters/residents/
// (background NPCs). Mirrors _iter_char_files() in server.py: ids are the bare
// filename stem, so they must stay unique across folders.
function* iterCharFiles(dir) {
  for (const entry of readdirSync(dir).sort()) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) {
      yield* iterCharFiles(path);
    } else if (entry.endsWith(".md")) {
      yield path;
    }
  }
}

const world = readFileSync(WORLD_FILE, "utf8");

const characters = {};
for (const path of iterCharFiles(CHARS_DIR)) {
  const id = path.split("/").pop().replace(/\.md$/, "");
  if (characters[id]) {
    console.warn(`  ! duplicate character id "${id}" — ${path} overwrites an earlier file`);
  }
  const { meta, body } = parseFrontmatter(readFileSync(path, "utf8"));
  characters[id] = { meta, body };
}

const banner = `// AUTO-GENERATED by build-data.mjs — do not edit by hand.\n` +
               `// Source: ../data/world.md and ../data/characters/**/*.md\n`;

const out =
  banner +
  `export const WORLD = ${JSON.stringify(world)};\n` +
  `export const CHARACTERS = ${JSON.stringify(characters, null, 2)};\n`;

writeFileSync(OUT_FILE, out);
console.log(`wrote ${OUT_FILE} — ${Object.keys(characters).length} characters, ${world.length} char world`);
